### ISSUE TITLE
installing openapi-generator-cli  gives below error

### ISSUE THREAD

**Issue by rukish** [Mastercard/mastercard-api-client-tutorial#25]
openapi-generator-cli version-manager set 5.1.0   
(node:59180) UnhandledPromiseRejectionWarning: Error: java.lang.UnsupportedClassVersionError: org/openapitools/codegen/OpenAPIGenerator : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Exception in thread "main"
    at C:\Users\Rukhiya\AppData\Roaming\npm\node_modules\@openapitools\openapi-generator-cli\main.js:636:32
    at ChildProcess.exithandler (child_process.js:397:5)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:675:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:59180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:59180) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will
terminate the Node.js process with a non-zero exit code.

Java version on my system
C:\windows\system32>java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

Please advise how to fix this issue.

**Comment by jaaufauvre** [comment]
Hi @rukish, we don't support the installation of OpenAPI Generator in this project.

If you have troubles installing OpenAPI Generator, an alternative to `npm install -g @openapitools/openapi-generator-cli` is to download and run the JAR [here](https://mvnrepository.com/artifact/org.openapitools/openapi-generator-cli).

Also, there are a number of ways to use OpenAPI Generator. See all options [here](https://openapi-generator.tech/docs/installation/).

Best regards,

**Comment by rukish** [comment]
Thanks. I resolved the issue.
